# Generated by Django 4.2.7 on 2023-12-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
