# Generated by Django 4.2.7 on 2023-12-04 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_category_active_alter_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
